# Generated by Django 4.2.4 on 2024-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_movie_name', models.CharField(max_length=255)),
                ('serial_no', models.CharField(max_length=50)),
                ('user_management', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
